# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  PROGRAM: roll
  BUILD_DIR: build

tasks:
  default:
    cmds:
      - task: build

  build:
    cmds:
      - go mod tidy
      - task: test
      - go build -o {{.BUILD_DIR}}/{{.PROGRAM}} cmd/main.go
    sources:
      - "**/*.go"
      - go.mod
      - exclude: "**/*_test.go"
    generates:
      - "{{.BUILD_DIR}}/{{.PROGRAM}}"

  test:
    cmds:
      - go test -cover -v
    sources:
      - "**/*.go"
      - go.mod

  fuzz:
    vars:
      FUZZTIME: '{{.FUZZTIME | default "10s"}}'
    cmds:
      - go test -fuzz Fuzz -fuzztime {{.FUZZTIME}}
