# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  default:
    cmds:
      - task: build

  build:
    cmds:
      - go mod tidy
      - task: test
      - go build -o build/roll cmd/main.go
    sources:
      - "**/*.go"
      - go.mod
      - exclude: "**/*_test.go"
    generates:
      - "build/roll"

  test:
    cmds:
      - go test -cover -v
    sources:
      - "**/*.go"
      - go.mod
      - exclude: cmd/**/*.go
